### ISSUE TITLE
Won't handle OpenStreetMap areas

### ISSUE THREAD

**Issue by stevevance** [fitnr/osm-tiny-maps#2]
I am trying to make an SVG map of Chicago featuring the following OpenStreetMap objects:
- highway=primary (line)
- highway=secondary (line)
- leisure=park (area)

The code will grab `leisure=park` objects and add them to the `.osm` file but it will not convert these to the shapefile because only "lines" (the highways, not Park areas) will (see line 114 in `Makefile`). 

I appended "multipolygons" to this line to include the park areas and executed. 

The `.osm` file was converted to two shapefiles, one for lines and one for multipolygons (expected, according to [these GDAL docs](http://www.gdal.org/drv_osm.html)). (It puts these, however, in a subfolder called `chicago-loop.shp`.)

The shapefile for the multipolygons doesn't have the tags split into columns, and instead has each feature's data concatenated (smashed!) into a single column. 
<img width="987" alt="screenshot 2016-02-28 00 10 32" src="https://cloud.githubusercontent.com/assets/1330459/13377782/b15cfc58-ddaf-11e5-8687-4b4759605a28.png">

Do you know what happened?

**Comment by fitnr** [comment]
I understand that there are two issues here - the correct handling of geometries and the correct handling of attributes.

I've fixed the handling of geometries with 03af9de. Now you can run 

```
make svgs GEOMETRY="lines multipolygons"
```

to download and draw both lines and areas. See the updated README for more info.

The problem with the attributes is related to [`osm.ini`](../../blob/master/osm.ini), the configuration file `ogr2ogr` uses to convert OSM data to geodata. The `[multipolygons]` section was commented out, so it wasn't properly handling the attributes. That should be fixed.
If there are specific attributes you want to become individual rows in the geojson, rather than part of an object in `other_tags`, you'll need to edit the lines beginning `attributes=` in the `[lines]` and `[multipolygons]` sections of `osm.ini`.

**Comment by fitnr** [comment]
(FYI, I just changed the Makefile to remove the dependency on JQ. The `BOUNDSFILE` in `config.ini` should now be a csv. Earlier versions of the project created that as an intermediate file, so you probably have it handy.)
